<div align="right">
<h5>
<a href="http://toastmastersdistrict61.org/sandbox/admin/officer.php" target="_parent" style="color:#ffffff;text-decoration: none;font-family: 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif;">Add Officer</a>&nbsp;&nbsp;&nbsp;&nbsp;
<a href="http://toastmastersdistrict61.org/sandbox/admin/activity_log.php" target="_parent" style="color:#ffffff;text-decoration: none;font-family: 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif;">Officer Activity log</a>&nbsp;&nbsp;&nbsp;&nbsp;
<a href="http://toastmastersdistrict61.org/sandbox/spring_reg_form_for_users.php" target="_parent" style="color:#ffffff;text-decoration: none;font-family: 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif;">New Spring Registrations</a>&nbsp;&nbsp;&nbsp;&nbsp;
<a href="http://toastmastersdistrict61.org/sandbox/reg_form_for_users.php" target="_parent" style="color:#ffffff;text-decoration: none;font-family: 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif;">New Fall Registrations</a>&nbsp;&nbsp;&nbsp;&nbsp;
<a href="http://toastmastersdistrict61.org/sandbox/admin/viewnewregistration.php" target="_parent" style="color:#ffffff;text-decoration: none;font-family: 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif;">View New Registrations</a>&nbsp;&nbsp;&nbsp;&nbsp;
<a href="http://toastmastersdistrict61.org/sandbox/admin/viewspringregistration.php" target="_parent" style="color:#ffffff;text-decoration: none;font-family: 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif;">View Spring Registrations</a>&nbsp;&nbsp;&nbsp;&nbsp;
<a href="http://toastmastersdistrict61.org/sandbox/admin/offlineusers.php" target="_parent" style="color:#ffffff;text-decoration: none;font-family: 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif;">View Offline Users</a>&nbsp;&nbsp;&nbsp;&nbsp;
<a href="http://toastmastersdistrict61.org/sandbox/admin/prod_form.php" target="_parent" style="color:#ffffff;text-decoration: none;font-family: 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif;">Add Products</a>&nbsp;&nbsp;&nbsp;&nbsp;
<a href="http://toastmastersdistrict61.org/sandbox/admin/viewproduct.php" target="_parent" style="color:#ffffff;text-decoration: none;font-family: 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif;">View Products</a>&nbsp;&nbsp;&nbsp;&nbsp;
<a href="http://toastmastersdistrict61.org/sandbox/admin/meals_form.php" target="_parent" style="color:#ffffff;text-decoration: none;font-family: 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif;">Add Meals</a>&nbsp;&nbsp;&nbsp;&nbsp;
<a href="http://toastmastersdistrict61.org/sandbox/admin/viewmeal.php" target="_parent" style="color:#ffffff;text-decoration: none;font-family: 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif;">View Meals</a>&nbsp;&nbsp;&nbsp;&nbsp;
<a href="http://toastmastersdistrict61.org/sandbox/admin/conf_form.php" target="_parent" style="color:#ffffff;text-decoration: none;font-family: 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif;">Add Conference</a>&nbsp;&nbsp;&nbsp;&nbsp;
<a href="http://toastmastersdistrict61.org/sandbox/admin/view_conf.php" target="_parent" style="color:#ffffff;text-decoration: none;font-family: 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif;">View Conference</a>&nbsp;&nbsp;&nbsp;&nbsp;
<a href="http://toastmastersdistrict61.org/sandbox/admin/clubs_form.php" target="_parent" style="color:#ffffff;text-decoration: none;font-family: 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif;">Add Clubs</a>&nbsp;&nbsp;&nbsp;&nbsp;
<a href="http://toastmastersdistrict61.org/sandbox/admin/clubsview.php" target="_parent" style="color:#ffffff;text-decoration: none;font-family: 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif;">View Clubs</a>&nbsp;&nbsp;&nbsp;&nbsp;
<a href="../lout.php" target="_parent" style="color:#ffffff;text-decoration: none;font-family: 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif;">Logout</a></h5></div>
